Nome = input("Digite o nome do cliente: ")
Dia = input("Digite o dia de vencimento: ")
Mês = input("Digite o mês de vencimento: ")
Valor = input("Digite o valor da fatura: ")
print("Olá,",Nome)
print("A sua fatura com vencimento em",Dia,"de",Mês,"no valor de R$",Valor,"está fechada.")
